version: '3.8'
services:

  zookeeper:
    image: bitnami/zookeeper:latest
    container_name: zookeeper
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    ports:
      - "2181:2181"
    networks:
      - fugito-net



  kafka:
    image: bitnami/kafka:latest
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - fugito-net

      
  auth-service:
    build: ./AuthService
    ports:
      - "5001:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__AuthConnection=Host=postgres;Port=5432;Database=authdb;Username=postgres;Password=postgres
    networks:
      - fugito-net

  product-service:
    build: ./ProductService
    ports:
      - "5002:8080"
    depends_on:
      - mongo
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoConnection=mongodb://mongo:27017
      - kafka__bootstrapServers = kafka:9092
    networks:
      - fugito-net

  cart-service:
    build: ./CartService
    ports:
      - "5003:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CartConnection=Host=postgres;Port=5432;Database=cartdb;Username=postgres;Password=postgres
    networks:
      - fugito-net

  stock-service:
    build: ./StockService
    ports:
      - "5004:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__StockConnection=Host=postgres;Port=5432;Database=stockdb;Username=postgres;Password=postgres
      - kafka__bootstrapServers=kafka:9092
    
    networks:
      - fugito-net

  mongo:
    image: mongo
    container_name: mongo-product
    ports:
      - "27017:27017"
    networks:
      - fugito-net
    volumes:
      - mongo_data:/data/db

  postgres:
    image: postgres
    container_name: postgres-fugito
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fugito_db
    networks:
      - fugito-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mongo_data:

networks:
  fugito-net:
