services:
  kafka:
    image: apache/kafka:3.8.0
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      # iD FOR THE SERVER OF THE CLUSTER
      - KAFKA_NODE_ID=1
      # DEFINING THE ROLES OF THE KAFKA BROKER
      - KAFKA_PROCESS_ROLES=broker, controller

      # LISTENERS AND ADVERTISED LISTENERS CONFIGURATION Kafka opens 9092 is for .net services  and 9093 is for controller communication
      - KAFKA_LISTENERS=PLAINTEXT://localhost:9092,CONTROLLER://:9093
      # ADVERTISED LISTENERS TO BE USED BY THE CLIENTS TO CONNECT TO KAFKA BROKER
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://localhost:9092

      - KAFKA_CONTROLLER_LiSTENER_NAME=CONTROLLER
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      
      
      
      #Select the voter to elect a leader for the controller quorum
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@localhost:9093
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR=1
      - KAFKA_TRANSACTION_STATE_LOG_MIN_ISR=1

      - KAFKA_CLUSTER_ID=RkVHSU8tS0FGRS1DTFVTVEVSLUNMQVNUZXItMQ==

    networks:
      - fugito-net

  auth-service:
    build: ./AuthService
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AuthConnection=Host=postgres;Port=5432;Database=fugito_db;Username=postgres;Password=postgres
    networks:
      - fugito-net

  product-service:
    build: ./ProductService
    ports:
      - "5002:8080"
    depends_on:
      - mongo
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__MongoConnection=mongodb://mongo:27017
      - kafka__bootstrapServers=kafka:9092
    networks:
      - fugito-net

  cart-service:
    build: ./CartService
    ports:
      - "5003:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CartConnection=Host=postgres;Port=5432;Database=cartdb;Username=postgres;Password=postgres
    networks:
      - fugito-net

  stock-service:
    build: ./StockService
    ports:
      - "5004:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__StockConnection=Host=postgres;Port=5432;Database=stockdb;Username=postgres;Password=postgres
      - kafka__bootstrapServers=kafka:9092

    networks:
      - fugito-net

  mongo:
    image: mongo
    container_name: mongo-product
    ports:
      - "27017:27017"
    networks:
      - fugito-net
    volumes:
      - mongo_data:/var/lib/mongo/data

  postgres:
    image: postgres
    container_name: postgres-fugito
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fugito_db
    networks:
      - fugito-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mongo_data:

networks:
  fugito-net:
