services:

  kafka-ui:
      image: provectuslabs/kafka-ui:latest
      container_name: kafka-ui
      ports:
        - "8080:8080"
      environment:
        KAFKA_CLUSTERS_0_NAME: local-kafka
        # finds the Kafka broker by its service name and port defined in docker-compose.yml
        KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
        KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: SASL_PLAINTEXT
        KAFKA_CLUSTERS_0_PROPERTIES_SASL_MECHANISM: PLAIN
        KAFKA_CLUSTERS_0_PROPERTIES_SASL_JAAS_CONFIG: org.apache.kafka.common.security.plain.PlainLoginModule required username="admin" password="admin-secret";
        

      networks:
        - fugito-net
      depends_on:
        - kafka
  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    ports:
      - "9092:9092"
    environment:


      #roles
      KAFKA_NODE_ID: "1"
      KAFKA_PROCESS_ROLES: "broker,controller"
      CLUSTER_ID: "5L6g3nShT-eMCtK--X86sw"


      #Listeners
      KAFKA_LISTENERS: "SASL_SSL://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093"
      KAFKA_ADVERTISED_LISTENERS: "SASL_SSL://kafka:9092"  # Advertised Listeners (Lo que el cliente .NET usará para conectar)
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "SASL_SSL:SASL_SSL,CONTROLLER:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: "SASL_SSL"
      KAFKA_CONTROLLER_LISTENER_NAMES: "CONTROLLER"
      # Configuración de KRaft QUORUM        
      KAFKA_CONTROLLER_QUORUM_VOTERS: "1@kafka:9093"


      
      # Habilitar SASL (SEGURIDAD BÁSICA AUTENTICACIÓN)
      KAFKA_SASL_ENABLED_MECHANISMS: "PLAIN"
      KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL: "PLAIN"
      # Configuración de usuario y contraseña
      KAFKA_OPTS: "-Djava.security.auth.login.config=/etc/kafka/kafka_jaas.conf"

      # habilitar autorización (ACLs)
      KAFKA_AUTHORIZER_CLASS_NAME: "org.apache.kafka.metadata.authorizer.StandardAuthorizer"
      KAFKA_SUPER_USERS: "User:admin"
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_BROKER_PRINCIPAL: "User:admin"

      # Configuración de SSL TLS (Cifrado)
      KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/secrets"
      KAFKA_SSL_KEYSTORE_FILENAME: "kafka.keystore.jks"

      KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/secrets"
      KAFKA_SSL_TRUSTSTORE_FILENAME: "kafka.truststore.jks"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: "HTTPS"
      KAFKA_SSL_KEY_CREDENTIALS: "key_creds"
      KAFKA_SSL_KEYSTORE_CREDENTIALS: "keystore_creds"
      KAFKA_SSL_TRUSTSTORE_CREDENTIALS: "truststore_creds"
      # Configuraciones de estabilidad
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: "1"
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: "1"
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: "0"

    volumes:
      - kafka_data:/var/lib/kafka/data
      - ./kafka_jaas.conf:/etc/kafka/kafka_jaas.conf
      - ./client.properties:/etc/kafka/client.properties
      - ./secrets:/etc/kafka/secrets


    networks:
      - fugito-net

  auth-service:
    build: ./AuthService
    ports:
      - "5001:5000"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
      - ConnectionStrings__AuthConnection=Host=postgres;Port=5432;Database=fugito_db;Username=postgres;Password=postgres
    networks:
      - fugito-net

  product-service:
    build: ./ProductService
    ports:
      - "5002:8080"
    depends_on:
      - mongo
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - MongoDBSettings__ConnectionString=mongodb://mongo:27017
      - MongoDBSettings__DatabaseName=ECommerceDb
      - MongoDBSettings__ProductsCollectionName=Products
      - Kafka__BootstrapServers=kafka:9092
    networks:
      - fugito-net

  cart-service:
    build: ./CartService
    ports:
      - "5003:8080"
    depends_on:
      - postgres
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__CartConnection=Host=postgres;Port=5432;Database=cartdb;Username=postgres;Password=postgres
    networks:
      - fugito-net

  stock-service:
    build: ./StockService
    ports:
      - "5004:8080"
    depends_on:
      - postgres
      - kafka
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__StockConnection=Host=postgres;Port=5432;Database=stockdb;Username=postgres;Password=postgres
      - kafka__bootstrapServers=kafka:9092

    networks:
      - fugito-net

  mongo:
    image: mongo
    container_name: mongo-product
    ports:
      - "27017:27017"
    networks:
      - fugito-net
    volumes:
      - mongo_data:/var/lib/mongo/data

  postgres:
    image: postgres
    container_name: postgres-fugito
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fugito_db
    networks:
      - fugito-net
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  mongo_data:
  kafka_data:

networks:
  fugito-net:
