KafkaServer {
    org.apache.kafka.common.security.plain.PlainLoginModule required
    username="admin"
    password="admin-secret"
    user_admin="admin-secret"
    user_stock_service="stock-user-secret"
    user_product_service="product-user-secret";
};